### ISSUE TITLE
Does this work with the sent2vec unigram wiki model

### ISSUE THREAD

**Issue by danielmorozoff** [swisscom/ai-research-keyphrase-extraction#11]
Hi there,

Currently attempting to launch in docker container.

Been trying to try this out with the unigram model, but am getting silent failures when attempting to load the embedding distributor:
`embedding_distributor = launch.load_local_embedding_distributor('en')`

It just closes out and crashes the docker container.

The command that launches the container:

`docker run  --memory=10g  -v /Desktop/ai-research-keyphrase-extraction/deps/sent2vec/models/wiki_unigrams.bin:/sent2vec/pretrained_model.bin -it keyphrase-extraction`

```
import launch
embedding_distributor = launch.load_local_embedding_distributor('en') <---FAILURE
```

Thanks in advance for your help.
Dan

**Comment by kamilbs** [comment]
Hi Dan,
It seems to be a memory issue , I tried with the bigram model and --memory=16g and it fails, whereas if I change the memory directly on the docker app everything works. Could you try to directly allow the memory from the app (Preferences > Advanced then apply and restart)
Best,
Kamil

**Comment by danielmorozoff** [comment]
memory prblm - closing issue
