### ISSUE TITLE
How to Evaluate the Model

### ISSUE THREAD

**Issue by shanalikhan** [swisscom/ai-research-keyphrase-extraction#14]
Hello, 
As its unsupervised, 
I want to know how can we evaluate the model and create the training data.
I have looked you have calculated f-measure

**Comment by kamilbs** [comment]
Hello,
We used publicly available dataset that contains text and keyphrases for each text (you can find more details in our paper). These keyphrases are used only for evaluation, to compare what the model extracted against the ground truth.

**Comment by shanalikhan** [comment]
Okay, as i dont find any dataset the target language for which i will be doing the keyphrase extraction, in Urdu language.

Do you know any guide lines to tag keyphrase from the News for different genre.

For example, if i target news for entertainment and politics in corpus, is there any guidelines that will allow me to know what really keyphrase is.
