### ISSUE TITLE
Error in importing ABC

### ISSUE THREAD

**Issue by dhariyalbhaskar** [swisscom/ai-research-keyphrase-extraction#15]
Thanks for the code.

I'm having mentioned issue. Will be glad if you could look into it.

![image](https://user-images.githubusercontent.com/20501023/51976611-21684580-24ab-11e9-8bbe-2987fdaeeef7.png)

**Comment by kamilbs** [comment]
Hi,
Which python version are you using ? I guess it comes from that, consider going python >= 3.6

**Comment by dhariyalbhaskar** [comment]
Sure, I will try to use higher version of python3
