### ISSUE TITLE
config.ini problem

### ISSUE THREAD

**Issue by stevenzhang027** [swisscom/ai-research-keyphrase-extraction#16]
what does model_path_de in config.ini.template mean?
in readme only one configuration ‘model_path’ is mentioned.

**Comment by kamilbs** [comment]
Hi,
You can leave it empty, this is here in case you load the embedding_distributor with german language 'de' (if you have a sent2vec model trained on german) , but we'll clean the code to remove it.
Thanks for pointing this out !
