### ISSUE TITLE
invalid value encountered in true_divide

### ISSUE THREAD

**Issue by Crescentz** [swisscom/ai-research-keyphrase-extraction#19]
raw_text = 'this is the text i want to extract keyphrases from'

kp1 = launch.extract_keyphrases(embedding_distributor, pos_tagger, raw_text, 10, 'en') 
/home1/zy/anaconda3/envs/py36pc2t/lib/python3.6/site-packages/ai-research-keyphrase-extraction/swisscom_ai/research_keyphrase/model/method.py:44: RuntimeWarning: invalid value encountered in true_divide
  0.5 + (sim_between_norm - np.nanmean(sim_between_norm, axis=0)) / np.nanstd(sim_between_norm, axis=0)

**Comment by kamilbs** [comment]
Hi this can happen when you have a very small number of candidates (less or equal than 2) which is not the case in general. Thanks for spotting this issue, I'll try to fix this special case. Meanwhile you can just try with slightly bigger sentence (that have at least 3 candidates).

**Comment by Crescentz** [comment]
thank you for your reply.it seems can be solved by:
    import numpy as np
    np.seterr(divide='ignore',invalid='ignore')
But it's not clear that there would be any risk. by the way , sent2vec has updated, and will this project be updated later?

**Comment by kamilbs** [comment]
Yes you are totally right, what you did just shut down the warning. There is a risk in fact , if you have only 2 candidates and want to extract only one (the best one) the result is wrong.

I'll have a look at the updates of s2v and see what is needed to make this project with the latest version. However the update won't be done in the following days unless someone want to do it through a PR :)
