### ISSUE TITLE
Model evaluation

### ISSUE THREAD

**Issue by nguyenxuanhoi2903** [swisscom/ai-research-keyphrase-extraction#20]
I using doc2vec with DUC01 dataset but results are not as expected? Can you help me?

**Comment by nguyenxuanhoi2903** [comment]
I have a question ? Document embedding using doc2vec, embedding of the candidate phrase using doc2vec or word2vec?

**Comment by princess96tq** [comment]
Did u fake result??? lol

**Comment by nguyenxuanhoi2903** [comment]
I used pre-trained Doc2Vec Models with English Wikipedia DBOW (1.4GB)

**Comment by kamilbs** [comment]
Hi to reproduce results in the paper ensure the following, the best results for DUC are given with the following HP : *beta=1* and you should *turn off the alias_threshold* which is an extra feature that we added only for convenience by puting *alias_threshold=1*

**Comment by nguyenxuanhoi2903** [comment]
<img width="864" alt="Screen Shot 2019-04-08 at 3 09 06 PM" src="https://user-images.githubusercontent.com/33613154/55708622-880c6100-5a10-11e9-9f9a-c4dbe7bebbab.png">
I also use gensim to infer the vectors for doc and candidates. I changed the parameter beta=1, N=15, alias_threshold=1 and this is the average result p=0.117, r=0.210, f1=0.148. 
I want to using sent2vec but I cant import sent2vec to the project.

**Comment by kamilbs** [comment]
Did you stem both the results and the gold using "PorterStemmer" of nltk ? (This is a practice done in almost all keyphrase extraction litterature). Also concerning your sent2vec installation can you open please another issue describing why you can't import sent2vec.

**Comment by nguyenxuanhoi2903** [comment]
I tried again with your tutorial but the results changed little.
Result with N=15 keyphrase
<img width="744" alt="Screen Shot 2019-04-11 at 12 07 20 AM" src="https://user-images.githubusercontent.com/33613154/55899906-20ad0780-5bf0-11e9-82cf-60eca33e31a8.png">

**Comment by nguyenxuanhoi2903** [comment]
I tried installing sent2vec but it failed when I run make .
I cant import sent2vec to project. I want to try with doc2vec but result not good.
Can you share the project with doc2vec for me?
<img width="739" alt="Screen Shot 2019-04-11 at 12 22 04 AM" src="https://user-images.githubusercontent.com/33613154/55900067-9022f700-5bf0-11e9-99b4-2642b36fd9fe.png">

**Comment by kamilbs** [comment]
I invite you to try the docker installation.
