### ISSUE TITLE
Getting Value Error when running launch.py in python3.5 Ubuntu 16.04 

### ISSUE THREAD

**Issue by rajeshkumargp** [swisscom/ai-research-keyphrase-extraction#23]
Getting Value Error when running launch.py 

+++++++++++++++++++++++++++++++++++++++
In [1]: import launch 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-abe38797ddf9> in <module>()
----> 1 import launch

~/ai-research-keyphrase-extraction/launch.py in <module>()
      2 from configparser import ConfigParser
      3 
----> 4 from swisscom_ai.research_keyphrase.embeddings.emb_distrib_local import EmbeddingDistributorLocal
      5 from swisscom_ai.research_keyphrase.model.input_representation import InputTextObj
      6 from swisscom_ai.research_keyphrase.model.method import MMRPhrase

~/ai-research-keyphrase-extraction/swisscom_ai/research_keyphrase/embeddings/emb_distrib_local.py in <module>()
      7 
      8 from swisscom_ai.research_keyphrase.embeddings.emb_distrib_interface import EmbeddingDistributor
----> 9 import sent2vec
     10 
     11 

__init__.pxd in init sent2vec()

ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

+++++++++++++++++++++++++++++++++++++++

**Comment by qyccc** [comment]
I got the same problem and run the command 
'''sudo pip3 install -U numpy '''
update the numpy can help
