### ISSUE TITLE
Inspec evaluation

### ISSUE THREAD

**Issue by laurita** [swisscom/ai-research-keyphrase-extraction#24]
Hey,
In the paper you mention that when evaluating the model on NUS dataset you union the keyphrases assigned by authors and annotators. Do you also union the controlled and uncontrolled keyphrases from Inspec dataset?

**Comment by kamilbs** [comment]
Hi,
For the Inspec Dataset, in order to compare to TopicRank paper (and original Hulth's paper) we used the *uncontrolled keyphrases* only (and apply stemming).

**Comment by laurita** [comment]
Thank you for a quick response!
