### ISSUE TITLE
Key phrases in other languages.

### ISSUE THREAD

**Issue by sejkko** [swisscom/ai-research-keyphrase-extraction#26]
I was wondering if there is a list of requirements we need to make sure are fulfilled to be able to run this system to extract key phrases in other languages. It seems to me that at least the Stanford CoreNLP server should be called with an appropriate language model, and the trained model used by SENT2VEC should be set appropriately. Could you say more about this?

**Comment by kamilbs** [comment]
Yes you are totally right, in addition to the PosTagger and sent2vec , you also need to define rules to extract candidate phrases.
