### ISSUE TITLE
Train new model for arabic and persian language

### ISSUE THREAD

**Issue by mahaghdam** [swisscom/ai-research-keyphrase-extraction#27]
Hello
I run the module with pretrained model, it works fine. I want to train new models for arabic and persian. I trained sent2vec model but I didn't work. Can you please guide me what else should I do? How can I use this module for other languages?

**Comment by mahaghdam** [comment]
Hello again
I used stanfordpostagger to tag the input text for my aimed languages. Convert different tags to considered tags. But I still have problems with extracting keyphrases. There is nothing as outout. 
Can you please guide me what I'm missing?

**Comment by kamilbs** [comment]
Hi !
Did you create a regular expression (based on pos tags) to extract candidate phrases ? I'll suggest you to check that you have rule(s) that extract candidate phrases in your language. [extractor.py](https://github.com/swisscom/ai-research-keyphrase-extraction/blob/master/swisscom_ai/research_keyphrase/model/extractor.py#L12)
