### ISSUE TITLE
std::bad_alloc Aborted

### ISSUE THREAD

**Issue by pbeneteau** [swisscom/ai-research-keyphrase-extraction#28]
Hi,

I managed to launch the program on my personal computer without any problem (16gb RAM). However, when I try to launch it on a server (8gb RAM), I get this error in 100% of the cases: 

`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
  Aborted`
I read that this error appears when there is no more RAM available.

Any idea to fix this issue?

**Comment by kamilbs** [comment]
Hello,
Yes it seems that you don't have enough available RAM to load the model, you can try the unigram model which is lighter.
