### ISSUE TITLE
How to extract keyphrase using Doc2Vec instead of Sent2Vec?

### ISSUE THREAD

**Issue by amit-dat** [swisscom/ai-research-keyphrase-extraction#8]
Hello, I've been trying to run the embedRank using Doc2Vec. What would be the changes made to the config.ini file and steps involved to setup the EmbedRank project using Doc2Vec instead of the sent2vec technique that is already mentioned in the Repo description?

Thanks!

**Comment by kamilbs** [comment]
Hello you'll have to create your own EmbeddingDistributor (such as EmbeddingDistributorLocal) , (see [embeddings package](https://github.com/swisscom/ai-research-keyphrase-extraction/tree/master/swisscom_ai/research_keyphrase/embeddings)) . All you have to implement is a method which takes a list of sentences as input and return an array ( number of sentences x embedding dimension).  To create this method you can search for a python interface for Doc2Vec. Finally to extract keyphrases : 

```
import launch
from swisscom_ai.research_keyphrase.embeddings.your_custom_distrib import YourDoc2VecDistributor
embedding_distributor = YourDoc2VecDistributor(...)
pos_tagger = launch.load_local_pos_tagger('en')
kp1 = launch.extract_keyphrases(embedding_distributor, pos_tagger, raw_text, 10, 'en')
```
