### ISSUE TITLE
Interactive session quits while trying to load embedding_distributor

### ISSUE THREAD

**Issue by miikargh** [swisscom/ai-research-keyphrase-extraction#9]
Hi!

First of all, thank you for sharing the code of the paper! It's super helpful.

I have a problem with the interactive session with docker. Basically what happens is that the session justs ends while loading the embedding_distributor.

Here's the command I use to launch the interactive session:
```
docker run -v ~/tests/embedrank/ai-research-keyphrase-extraction/wiki_unigrams.bin:/sent2vec/pretrained_model.bin -it keyphrase-extraction
```

and here's the docker logs from that session:
```
Python 3.6.5 (default, Apr  4 2018, 23:11:43)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import launch
>>> embedding_distributor = launch.load_local_embedding_distributor('en')
```
Nothing really happens, no error, not anything. It just quits. What am I doing wrong here? Any help much appreciated.

**Comment by kamilbs** [comment]
Hello , 
You should ensure that you have enough memory in your container (because the embedding takes a lot of space in RAM). If the problem still persist I advise you to go for the local installation which normally works perfectly fine.

Best,
Kamil

**Comment by miikargh** [comment]
I expanded the container memory from 2GB to 16GB and it worked. Thank you very much!

**Comment by kamilbs** [comment]
No problem !  :)
